// Auto-generated by LibreLane
module sram(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input cs,
  input we_n,
  input oe_n,
  input[1:0] row_addr,
  input[1:0] col_addr,
  input data_in,
  output data_out,
  output data_out_bar
);
endmodule
