/* Generated by Yosys 0.62 (git sha1 7326bb7d6641500ecb285c291a54a662cb1e76cf, clang++ 21.1.2 -fPIC -O3) */

module sg13g2_Corner();
endmodule

module sg13g2_Filler1000();
endmodule

module sg13g2_Filler10000();
endmodule

module sg13g2_Filler200();
endmodule

module sg13g2_Filler2000();
endmodule

module sg13g2_Filler400();
endmodule

module sg13g2_Filler4000();
endmodule

module sg13g2_IOPadAnalog(pad, padres);
  inout pad;
  wire pad;
  inout padres;
  wire padres;
endmodule

module sg13g2_IOPadIOVdd(vss, vdd, iovss, iovdd);
  inout vss;
  wire vss;
  inout vdd;
  wire vdd;
  inout iovss;
  wire iovss;
  inout iovdd;
  wire iovdd;
endmodule

module sg13g2_IOPadIOVss(vss, vdd, iovss, iovdd);
  inout vss;
  wire vss;
  inout vdd;
  wire vdd;
  inout iovss;
  wire iovss;
  inout iovdd;
  wire iovdd;
endmodule

module sg13g2_IOPadIn(pad, p2c);
  inout pad;
  wire pad;
  output p2c;
  wire p2c;
endmodule

module sg13g2_IOPadInOut16mA(pad, c2p, c2p_en, p2c);
  inout pad;
  wire pad;
  input c2p;
  wire c2p;
  input c2p_en;
  wire c2p_en;
  output p2c;
  wire p2c;
endmodule

module sg13g2_IOPadInOut30mA(pad, c2p, c2p_en, p2c);
  inout pad;
  wire pad;
  input c2p;
  wire c2p;
  input c2p_en;
  wire c2p_en;
  output p2c;
  wire p2c;
endmodule

module sg13g2_IOPadInOut4mA(pad, c2p, c2p_en, p2c);
  inout pad;
  wire pad;
  input c2p;
  wire c2p;
  input c2p_en;
  wire c2p_en;
  output p2c;
  wire p2c;
endmodule

module sg13g2_IOPadOut16mA(pad, c2p);
  inout pad;
  wire pad;
  input c2p;
  wire c2p;
endmodule

module sg13g2_IOPadOut30mA(pad, c2p);
  inout pad;
  wire pad;
  input c2p;
  wire c2p;
endmodule

module sg13g2_IOPadOut4mA(pad, c2p);
  inout pad;
  wire pad;
  input c2p;
  wire c2p;
endmodule

module sg13g2_IOPadTriOut16mA(pad, c2p, c2p_en);
  inout pad;
  wire pad;
  input c2p;
  wire c2p;
  input c2p_en;
  wire c2p_en;
endmodule

module sg13g2_IOPadTriOut30mA(pad, c2p, c2p_en);
  inout pad;
  wire pad;
  input c2p;
  wire c2p;
  input c2p_en;
  wire c2p_en;
endmodule

module sg13g2_IOPadTriOut4mA(pad, c2p, c2p_en);
  inout pad;
  wire pad;
  input c2p;
  wire c2p;
  input c2p_en;
  wire c2p_en;
endmodule

module sg13g2_IOPadVdd(vss, vdd, iovss, iovdd);
  inout vss;
  wire vss;
  inout vdd;
  wire vdd;
  inout iovss;
  wire iovss;
  inout iovdd;
  wire iovdd;
endmodule

module sg13g2_IOPadVss(vss, vdd, iovss, iovdd);
  inout vss;
  wire vss;
  inout vdd;
  wire vdd;
  inout iovss;
  wire iovss;
  inout iovdd;
  wire iovdd;
endmodule
